### ISSUE TITLE
Stack-Graph v2 test fixing

### ISSUE THREAD

**Issue by Orzelius** [garden-io/garden#3113]
**Goal 1:** It compiles
**Goal 2:** It passes

**Goal 2 progress.**

**Update from 13.02.2023**
Most of the failing tests were fixed in #3738
There are still a few failures:
  - [x] `tasks/resolve-action.ts` -> partially fixed in #3738, there are some `git` command execution failures
  - [x] `router/base.ts` -> some `git` command execution failures, the same as above
  - [x]  #3549 

Unit tests with build issues to be fixed by packages in `core/test/unit/src/`
- [x] #3707
- [x] #3544
- [x] cli
  - [x] cli.ts -> resolve one TODO-G2 and fix `connects the process to an external server instance if available + some assertion failures
  - [x] #3572
- [x] #3574
- [x] cloud
  - [x] #3727
- [x] garden/solver.ts -> need to implement some new tests
- [x] #3501
- [x] commands
  - [x] #3677
  - [x] #3678
  - [x] #3679
  - [x] #3695
- [x] config
  - [x] template-contexts/module.ts -> completed in #3738 
  - [x] #3506
  - [x] #3717
- [x] graph -> need to implement new tests
- [x] plugins
  - [x] container
    - [x] #3629
    - [x] #3569
  - [x] #3547 
- [x] server -> fixed in #3738 
  - [x] core-event-stream.ts
  - [x] server.ts
- [x] tasks (mostly fixed via #3381, but some failures remain)
  - [x] deploy.ts 
  - [x] helpers.ts
  - [x] resolve-provider.ts
  - [x] run.ts
  - [x] test.ts -> fixed in #3738 
- [x] types @Orzelius 
- [x] #3528
- [x] #3723
- [x] vcs
  - [x] git.ts -> #3546
  - [x] vcs.ts -> some errors in assertions (need to figure out whether those are code bugs or bad assertions in the tests)
- [x] #3540
- [x] #3595
- [x] #3530
- [x] outputs.ts @Orzelius 
- [x] #3622
- [x] #3698
- [x] #3554
- [x] config-store.ts -> done by some past fixes 

Integration tests with build issues to be fixed by packages in `core/test/integ/src/plugins/`
- [x] #3675
- [x] #3583 
- [x] kubernetes
  - [x] commands @Orzelius 
  - [x] container 
    - [x] build
    - [x] container.ts
    - [x] deployment.ts
    - [x] ingress.ts 
    - [x] logs.ts
    - [x] run.ts
  - [x] helm 
    - [x] common.ts
    - [x] deployment.ts
    - [x] run.ts
    - [x] test.ts
  - [x] kubernetes-module 
    - [x] common.ts
    - [x] handlers.ts
    - [x] run.ts
    - [x] test.ts
  - [x] volume 
  - [x] dev-mode.ts 
  - [x] local-mode.ts -> to be fixed in #3937 
  - [x] run.ts 
  - [x] system.ts 
  - [x] task-results.ts 
  - [x] util.ts 

**Goal 1 progress.**

Unit tests with build issues to be fixed by packages in `core/test/unit/src/`
- [x] actions.ts @vvagaytsev 
- [x] config-graph.ts @vvagaytsev 
- [x] garden.ts @vvagaytsev 
- [x] outputs.ts @Orzelius 
- [x] ~runtime-context.ts @vvagaytsev~
- [x] build-staging @vvagaytsev 
- [x] commands @vvagaytsev 
  - [x] create
  - [x] get
  - [x] run
  - [x] build.ts
  - [x] call.ts
  - [x] delete.ts
  - [x] deploy.ts
  - [x] dev.ts
  - [x] helpers.ts
  - [x] logs.ts
  - [x] publish.ts
  - [x] test.ts
- [x] config @Orzelius 
- [x] enterprise @Orzelius 
- [x] graph @vvagaytsev 
- [x] plugins @Orzelius 
- [x] tasks @vvagaytsev
- [x] types @Orzelius 

Integration tests with build issues to be fixed by packages in `core/test/integ/src/plugins/`
- [x] hadolint @Orzelius 
- [x] kubernetes
  - [x] commands @vvagaytsev 
  - [x] container @vvagaytsev 
    - [x] build
    - [x] container.ts
    - [x] deployment.ts
    - [x] ingress.ts @Orzelius 
    - [x] logs.ts
    - [x] run.ts
  - [x] helm @vvagaytsev 
    - [x] common.ts
    - [x] deployment.ts
    - [x] run.ts
    - [x] test.ts
  - [x] kubernetes-module @vvagaytsev 
    - [x] common.ts
    - [x] handlers.ts
    - [x] run.ts
    - [x] test.ts
  - [x] volume @Orzelius 
  - [x] dev-mode.ts @vvagaytsev 
  - [x] local-mode.ts @vvagaytsev 
  - [x] run.ts @Orzelius 
  - [x] system.ts @Orzelius 
  - [x] task-results.ts @vvagaytsev 
  - [x] util.ts @Orzelius

**Comment by Orzelius** [comment]
closed with https://github.com/garden-io/garden/pull/3944
