### ISSUE TITLE
SGv2 fix command tests

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#3501]
SGv2 fix command unit tests:

* [x] create  -> fixed by some recent bug fixes in the core code
* [x] get // ~need to implement some new tests (TODOs)~ ->all tests have been fixed in #3588 
  * [x] get-config.ts
  * [x] get-graph.ts
  * [x] get-linked-repos.ts
  * [x] get-run-result.ts -> fixed in #3580 
  * [x] get-status.ts
  * [x] get-test-result.ts
  * [x] get-tests.ts
* [x] build.ts
* [x] call.ts
* [x] delete.ts
* [x] deploy.ts
* [x] dev.ts -> some findings are shared in #3581
* [x] exec.ts
* [x] helpers.ts -> fixed by some recent bug fixes in the core code
* [x] link.ts -> fixed by some recent bug fixes in the core code
* [x] logs.ts
* [x] publish.ts Orzelius (mostly done, but some unrelated errors remain that come from elsewhere)
* [x] run.ts // need to implement some new tests (TODOs)
* [x] run-workflow.ts
* [x] self-update.ts
* [x] test.ts
* [x] unlink.ts -> fixed via bug fixes somewhere else
* [x] update-remote.ts -> fixed via bug fixes somewhere else

**Comment by vvagaytsev** [comment]
Closing this as done.
