### ISSUE TITLE
0.13 fix tests in garden.ts

### ISSUE THREAD

**Issue by Walther** [garden-io/garden#3530]
- [x] Some trivial assertion fixes in https://github.com/garden-io/garden/pull/3532
- [x] #3709 
- [x] `resolveModules` errors -> fixed in #3720 
- [x] `getConfigGraph` errors -> fixed in #3710
- [x] `when a provider has an augmentGraph handler` context errors
- [x] `resolveModuleVersion` errors
- [x] fix some schema validation issues
- [x] `warnings` errors -> fixed in #3722
