### ISSUE TITLE
Fix tests in plugins/exec

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#3549]
Fix specs in `plugins/exec/exec.ts`. The problematic specs are:
* [ ] `should propagate task logs to runtime outputs` -> fails on template string resolution: `Invalid template string (${runtime.tasks.task-a.outputs.log}): Could not find key task-a under runtime.tasks`. **Possible cause:** the [`ActionSpecContext`](https://github.com/garden-io/garden/blob/0.13/core/src/tasks/resolve-action.ts#L146) is not complete. -> to be fixed in #3694 
* [x] `should copy artifacts after test runs` -> fixed test action key in #3551 (https://github.com/garden-io/garden/pull/3551/commits/8b16dac3d877f69e348daf96baad655ee02a4377)
* [x] `should throw if a local exec module has a build.copy spec` -> fixed in #3594 
* [x] `build` -> fixed test assertions in #3551 (https://github.com/garden-io/garden/pull/3551/commits/27e2f8163e46d4bd48ab13806eb1195b1b8c95dc)
* [ ] `testExecModule` -> likely some actions misconfiguration at `internal.basePath: "TODO-G2"` -> draft PR is #3566 
  * [ ] `should run the test command in the module dir if local true`
  * [ ] `should receive module version as an env var`
* [x] `runExecTask` -> fixed test assertions in #3551 (https://github.com/garden-io/garden/pull/3551/commits/bb04022fab4866284dd70250ff2e0b6e77aae407) - see `TODO-G2` comments in the commit
* [ ] `convert` -> implement missing tests
  * -> partially fixed in #3647 
  * -> more fixes were done in #3718 
  * -> the last fixes were done in #3689  
* [x] `services`
  * [x] `deployExecService` -> fixed test assertions in #3551 (https://github.com/garden-io/garden/pull/3551/commits/3f3c997d107653cebfc4fe7b352fb4d7a05ebc5e)
  * [x] `getExecServiceStatus` -> fixed test assertions in #3551 (https://github.com/garden-io/garden/pull/3551/commits/9dc05a5f1843d68ed910d5e1b5b323093f84749e)
  * [x] `deleteExecService` -> fixed in #3551 (https://github.com/garden-io/garden/pull/3551/commits/e18eeb032dd6bcd42790a875cd263e1ebfb0b1fc and https://github.com/garden-io/garden/pull/3551/commits/80b447f86b34a1cd35a52fc4f30b0b473ef19eec)

**Comment by vvagaytsev** [comment]
Completed in #3689
