### ISSUE TITLE
Request for Docs

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#3961]
## Summary

This is a catchall issue for missing documentation, at least while we work through the initial batch.

We believe docs are an integral part of the product experience and want to seek feedback from our community on the topics you think are missing and/or want to see prioritised. 

Please tell us what you think in the comments and we'll update the issue body accordingly 🙏

In the future we may decide to have individual issues for each topic but for now it feels useful to keep it all in one place. 

## Request for Docs

The sections below map to sections in our documentation. 

Note that we also need to update a lot of guides with the 0.13 release, e.g. everything under the "Using Garden" section, but we're not listing that specifically here. 

### Welcome

- [x] The [Welcome!](https://docs.garden.io/) guide should explain in more detail how to read the docs. 

### Basics

- [x] [The Stack Graph (Terminology)](https://docs.garden.io/basics/stack-graph) guide could be folded into the [How Garden Works](https://docs.garden.io/basics/how-garden-works) guide or otherwise updated after 0.13.
- [x] Add a "Use Cases" guide that explain how teams actually use Garden "in the real world". This could also be an entire section with sub pages (@eysi09 is working on this). Furthermore, each use case should link to a "how to" for that specific use case. 
 
### Quickstart

- [ ] Better installation guide for local K8s and a dedicated troubleshooting section. The content proper should probably be on the ["Install Local Kubernetes"](https://docs.garden.io/kubernetes-plugins/local-k8s/install) page but clearly visible from the quick start guide. Should also address [this comment](https://github.com/garden-io/garden/issues/3961#issuecomment-1473451060) and [this comment](https://github.com/garden-io/garden/issues/3961#issuecomment-1473911558).

### Using Garden

- [ ] We should have a better and more visible guide on including and excluding files. This is a common source of confusion and is currently quite hidden away in the [Configuration Overview](https://docs.garden.io/using-garden/configuration-overview) guide.

### Remote K8s set-up guides

These guides can be found in the [Remote K8s Plugin Configuration](https://docs.garden.io/kubernetes-plugins/remote-k8s) section of our docs. They do not depend on the 0.13 release and can be improved right away. 

- [ ] Creating a cluster on AWS (currently a stub).
- [ ] Creating a cluster on GCP (currently a stub).
- [ ] Creating a cluster on Azure (currently a stub).
- [ ] Setting a up container registry on Azure (currently a stub).
- [ ] In general review and improve guides on setting up container registries and using for in-cluster building. Note that there's also an item under "Best practices" for cache configuration. 
- [ ] Set up Ingress, TLS, and DNS (currently a stub). This is a common support topic and could be documented a lot better with examples for different providers and set ups. 

### K8s action types

- [ ] Fill in guide on Helm pod

### Guides

- [x] Add a section on "Rolling Garden out to developers" to the [Adopting Garden](https://docs.garden.io/guides/adopting-garden) guide. 
- [ ] Add a guide on the different Garden container images, what they contain and how to use them in CI.
- [ ] Add a guide on using the Garden GitHub action. Can also be a section in the [Using Garden in CI](https://docs.garden.io/guides/using-garden-in-ci) guide which is currently a little dated. 
- [ ] Debugging common K8s issues. 

### Best practices

This section does not exist yet. Most the topics here should be added after our 0.13 release since they depend on functionality introduced there.

- [ ] Dev / sync mode for compiled languages with specific examples for common languages like Java, Typescript (ok it's transpiled), Rust, (other?).
- [ ] Dev / sync mode for interpreted languages with specific examples for common languages like Python, Ruby, Javascript, (other?).
- [ ] Configuring Dockerfiles and K8s manifests for dev mode. (See also example on how to override stuff when a module is running in devMode, for example overriding the dockerfile like this dockerfile: "${command.params contains 'dev' ? 'Dockerfile.dev' : 'Dockerfile'}" from https://github.com/garden-io/garden/issues/3961#issuecomment-1472354265). 
- [ ] Running tests during inner loop development.
- [ ] Best practices for writing Dockerfiles with examples for common languages. 
- [ ] Best practices for cache configuration for in-cluster building. 

### References

- [ ] Inline example, or just a pointer to the quickstart project from the kubernetes module docs (see https://github.com/garden-io/garden/issues/3961#issuecomment-1472354265)

### Section TBD

Example on how to override stuff when a module is running in devMode, for example overriding the dockerfile like this dockerfile: "${command.params contains 'dev' ? 'Dockerfile.dev' : 'Dockerfile'}"

**Comment by pepov** [comment]
First of all nice work all around the docs already!

I was missing two minor things:
- inline example, or just a pointer to the quickstart project from the kubernetes modul docs: https://docs.garden.io/reference/module-types/kubernetes
- example on how to override stuff when a module is running in devMode, for example overriding the dockerfile like this `dockerfile: "${command.params contains 'dev' ? 'Dockerfile.dev' : 'Dockerfile'}"`

**Comment by pepov** [comment]
Another one: in the installation guide I cannot find any mention of the ingress controller and how you enable/install one for the specific provider in order to access the services.

**Comment by pepov** [comment]
I just realized what is happening behind the scenes. I was nuking my local kubernetes cluster to test with a new one (minikube vs docker desktop). I remembered I had a warning message about the ingressclass and that I enabled nginx ingress in minikube previously, so without thinking about it too much I installed nginx-ingress to my new docker desktop cluster as well. It seemed to work okay, but my coworker also tried and it failed for him with an error message:
```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists...
```

Strange enough it did not happen to me, not after resetting my docker desktop kubernetes, but then I realized I might be missing something. I actually forgot to remove the `.garden` folder. When I did the installation failed for me as well, but with a different error message. The installation timed out waiting for a resource, which was the loadbalancer pending in my local k8s. I had to restart docker to finally make it work. And of course as I realized, I don't have to install ingress, because garden does it for me (despite the warning message).

I also found out, that the provider setup can be triggered through:
```
garden plugins local-kubernetes cluster-init
```

Not sure what I would suggest to do here, but maybe discussing a little bit about how the ingress works and is built into garden with the provider init would be helpful. Also some words about nuking the garden setup could help others as well.

**Comment by eysi09** [comment]
Thanks so much for the feedback and my apologies for the tardy reply! 

I'll add your suggestions to the main issue body. 

As for you last comment, this is exactly the kind of user experience that is way to common and we want to try and preempt. 

Sometimes it's K8s, sometimes it's Garden but we can in any case do better when it comes to error messages and making sure to at least document the happy "getting started" path with a troubleshooting section at the bottom. 

I'll make a note of that in the issue body comment as well.

**Comment by eysi09** [comment]
Some other general notes after recent changes:

- I personally don't think the Bonsai migration guide should belong under "Tutorials". 
- We need banners / info text on the fact that you're looking at the Bonsai (0.13) docs by default and where to find the Acorn (0.12) docs. 
- We need to draw more attention to the "Action" docs, at the moment they're kind of at the bottom under the Using Garden section.
- This: #4472

**Comment by eysi09** [comment]
We are desperately missing specific docs for developers that don't need to worry about config or getting started but just using the CLI on an existing project. 

Also related to #4472

**Comment by eysi09** [comment]
I'm closing this in favour of creating individual issues for missing docs.
