### ISSUE TITLE
0.13: Update docs aggregate 

### ISSUE THREAD

**Issue by Orzelius** [garden-io/garden#4067]
This is a list of docs that need to be updated. Feel free to put your name behind a doc or a section if you feel like working on any of these.

I will try to take care of the rest.

- [x] advanced
  - [x] [advanced/cert-manager-integration.md](https://github.com/garden-io/garden/tree/0.13/docs/advanced/cert-manager-integration.md) to be removed -> removed in #4085
  - [x] [advanced/custom-commands.md](https://github.com/garden-io/garden/tree/0.13/docs/advanced/custom-commands.md) @Walther  https://github.com/garden-io/garden/pull/4325
    - [x] also remove experimental flag
  - [x] [advanced/using-remote-sources.md](https://github.com/garden-io/garden/tree/0.13/docs/advanced/using-remote-sources.md)
- [x] basics
  - [x] [basics/how-garden-works.md](https://github.com/garden-io/garden/tree/0.13/docs/basics/how-garden-works.md)
  - [x] [basics/quickstart.md](https://github.com/garden-io/garden/tree/0.13/docs/basics/quickstart.md) @ShankyJS
    - [x] also update https://github.com/garden-io/quickstart-example @worldofgeese 
  - [x] [basics/stack-graph.md](https://github.com/garden-io/garden/tree/0.13/docs/basics/stack-graph.md)
- [x] guides
  - [x] [guides/adopting-garden.md](https://github.com/garden-io/garden/tree/0.13/docs/guides/adopting-garden.md)
  - [x] [guides/code-synchronization.md](https://github.com/garden-io/garden/tree/0.13/docs/guides/code-synchronization.md)
  - [x] [guides/hot-reload.md](https://github.com/garden-io/garden/tree/0.13/docs/guides/hot-reload.md) to be removed
  - [x] [guides/migrating-from-docker-compose.md](https://github.com/garden-io/garden/tree/0.13/docs/guides/migrating-from-docker-compose.md) -> https://github.com/garden-io/garden/pull/4235
    - [x] Also update https://github.com/garden-io/garden-docker-compose -> https://github.com/garden-io/garden-docker-compose/pull/2
  - [x] [guides/namespaces.md](https://github.com/garden-io/garden/tree/0.13/docs/guides/namespaces.md)
  - [x] [guides/running-service-in-local-mode.md](https://github.com/garden-io/garden/tree/0.13/docs/guides/running-service-in-local-mode.md) 
- [x] k8s-plugins @Orzelius 
  - [x] k8s-plugins/advanced
    - [x] [k8s-plugins/advanced/deploying-to-production.md](https://github.com/garden-io/garden/tree/0.13/docs/k8s-plugins/advanced/deploying-to-production.md)
  - [x] k8s-plugins/module-types (folder renamed to `action-types`)
    - [x] [k8s-plugins/module-types/README.md](https://github.com/garden-io/garden/tree/0.13/docs/k8s-plugins/module-types/README.md)
    - [x] [k8s-plugins/module-types/configmap.md](https://github.com/garden-io/garden/tree/0.13/docs/k8s-plugins/module-types/configmap.md)
    - [x] [k8s-plugins/module-types/container.md](https://github.com/garden-io/garden/tree/0.13/docs/k8s-plugins/module-types/container.md)
    - [x] [k8s-plugins/module-types/helm.md](https://github.com/garden-io/garden/tree/0.13/docs/k8s-plugins/module-types/helm.md)
    - [x] [k8s-plugins/module-types/kubernetes.md](https://github.com/garden-io/garden/tree/0.13/docs/k8s-plugins/module-types/kubernetes.md)
    - [x] [k8s-plugins/module-types/persistentvolumeclaim.md](https://github.com/garden-io/garden/tree/0.13/docs/k8s-plugins/module-types/persistentvolumeclaim.md)
  - [x] k8s-plugins/remote-k8s
    - [x] [k8s-plugins/remote-k8s/configure-provider.md](https://github.com/garden-io/garden/tree/0.13/docs/k8s-plugins/remote-k8s/configure-provider.md)
    - [x] k8s-plugins/remote-k8s/configure-registry
      - [x] [k8s-plugins/remote-k8s/configure-registry/README.md](https://github.com/garden-io/garden/tree/0.13/docs/k8s-plugins/remote-k8s/configure-registry/README.md)
        - [x] remove in cluster registry mentions
- [ ] misc 
  - [x] [misc/faq.md](https://github.com/garden-io/garden/tree/0.13/docs/misc/faq.md)
  - [ ] [misc/telemetry.md](https://github.com/garden-io/garden/tree/0.13/docs/misc/telemetry.md) @mkhq 
    - [ ] I think we changed something about the opt-in default but I can't remember
  - [x] [misc/troubleshooting.md](https://github.com/garden-io/garden/tree/0.13/docs/misc/troubleshooting.md) 
- [x] other-plugins @garden-io/core 
  - [x] [other-plugins/container.md](https://github.com/garden-io/garden/tree/0.13/docs/other-plugins/container.md) -> #4282
  - [x] [other-plugins/exec.md](https://github.com/garden-io/garden/tree/0.13/docs/other-plugins/exec.md) -> #4278
- [x] pulumi-plugin @srihas-g -> #4261
  - [x] [pulumi-plugin/about.md](https://github.com/garden-io/garden/tree/0.13/docs/pulumi-plugin/about.md)
  - [x] [pulumi-plugin/configure-modules.md](https://github.com/garden-io/garden/tree/0.13/docs/pulumi-plugin/configure-modules.md)
  - [x] [pulumi-plugin/configure-provider.md](https://github.com/garden-io/garden/tree/0.13/docs/pulumi-plugin/configure-provider.md)
- [x] terraform-plugin @Walther -> #4296
  - [x] [terraform-plugin/about.md](https://github.com/garden-io/garden/tree/0.13/docs/terraform-plugin/about.md)
  - [x] [terraform-plugin/configure-modules.md](https://github.com/garden-io/garden/tree/0.13/docs/terraform-plugin/configure-modules.md)
  - [x] [terraform-plugin/configure-provider.md](https://github.com/garden-io/garden/tree/0.13/docs/terraform-plugin/configure-provider.md)
- [x] tutorials 
  - [x] tutorials/your-first-project
    - [x] [tutorials/your-first-project/1-initialize-a-project.md](https://github.com/garden-io/garden/tree/0.13/docs/tutorials/your-first-project/1-initialize-a-project.md)
    - [x] [tutorials/your-first-project/3-deploy-and-test.md](https://github.com/garden-io/garden/tree/0.13/docs/tutorials/your-first-project/3-deploy-and-test.md)
    - [x] [tutorials/your-first-project/4-configure-your-project.md](https://github.com/garden-io/garden/tree/0.13/docs/tutorials/your-first-project/4-configure-your-project.md)
- [x] using-garden 
  - [x] [using-garden/config-templates.md](https://github.com/garden-io/garden/tree/0.13/docs/using-garden/config-templates.md) 
  - [x] [using-garden/configuration-overview.md](https://github.com/garden-io/garden/tree/0.13/docs/using-garden/configuration-overview.md)
    - [x] add links to the actions.md guide from the task below
  - [x] [using-garden/modules.md](https://github.com/garden-io/garden/tree/0.13/docs/using-garden/modules.md)
  - [x] create using-garden/actions.md (modules.md can be taken as a base)
    - [x] need to resolve some TODOs -> #4270
    - [x] need to review and improve style and wording
  - [x] [using-garden/projects.md](https://github.com/garden-io/garden/tree/0.13/docs/using-garden/projects.md)
  - [x] [using-garden/services.md](https://github.com/garden-io/garden/tree/0.13/docs/using-garden/services.md)
  - [x] [using-garden/tasks.md](https://github.com/garden-io/garden/tree/0.13/docs/using-garden/tasks.md)
  - [x] [using-garden/tests.md](https://github.com/garden-io/garden/tree/0.13/docs/using-garden/tests.md)
  - [x] [using-garden/using-the-cli.md](https://github.com/garden-io/garden/tree/0.13/docs/using-garden/using-the-cli.md)
    - [x] -> ~add "Creating an action" section (requires `garden create action` command or similar machinery~ -> WIP PR is #4124) -> the command will be implemented in further patch release, it's not a blocker for `0.13.0`
  - [x] [using-garden/variables-and-templating.md](https://github.com/garden-io/garden/tree/0.13/docs/using-garden/variables-and-templating.md)
  - [x] #4292
- [ ] [welcome.md](https://github.com/garden-io/garden/tree/0.13/docs/welcome.md)

- [x] reference docs @Orzelius 
  - [x] add deprecation warning to module references and module-types readme
  - [x] look trough provider docs and fix appropriately
  - [x] looks through other reference docs and fix appropriately

**Comment by Orzelius** [comment]
@10ko can you take care of the [guides/migrating-from-docker-compose.md](https://github.com/garden-io/garden/tree/0.13/docs/guides/migrating-from-docker-compose.md) guide and the accompanying example as you wrote them originally?

**Comment by shumailxyz** [comment]
I'd suggest that we should also visit the sidebar and order of menu links in sidebar. Would be nice to move the Bonsai related pages above older 0.12 specific pages. (e.g. Actions page on top order under Using Garden seciton )

**Comment by ShankyJS** [comment]
@Orzelius / @thsig

@worldofgeese and I are going to take a look into the Quickstart section and update it to Bonsai, we are thinking about adding more structure to it and adding some extra wins, maybe even presenting interactive `dev` command in the process.

**Comment by vvagaytsev** [comment]
@stefreak @twelvemo could you help with the[ workflows guide](https://github.com/garden-io/garden/blob/0.13/docs/using-garden/workflows.md) update, please?

**Comment by Orzelius** [comment]
completed.
