### ISSUE TITLE
Merge 0.13 into main

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#4271]
Pair with @garden-io/core and @stefreak 

Plan:
* [x] Release `0.12.56`
* [x] Backup current `latest-release` to `latest-release-0.12`
* [x] Backup current `main` to `0.12`
* [x] Change the base of [all main-based PRs](https://github.com/garden-io/garden/pulls?q=is%3Apr+is%3Aopen+base%3Amain) to `0.12`
* [x] Check the `test-release.sh` script - remove unnecessary (unrelated) test steps like module creation
  * [x] partially done via #4315 
  * [x] need to test `deploy --sync` step
* [x] Revisit and update CircleCI configs in
  * [x] `main`
  * [x] `0.13`
  * [x] Verify the validity `edge-bonsai` tags
* [x] Do the necessary Docker build changes in `0.13` -> @stefreak (pair with @vvagaytsev and @Walther)
* [x] Do the merge
  * [x] Backup `0.13`
    * [x] pre-merge backup: https://github.com/garden-io/garden/tree/0.13-backup-2023-05-18-pre-merge
    * [x] post-merge backup: https://github.com/garden-io/garden/tree/0.13-backup-2023-05-18-post-merge
  * [x] Merge `main` to `0.13` -> #4314
  * [x] Merge `0.13` to `main`, resolve conflicts if any (conflicts are not expected after the merge above ) -> this should automatically change the base of [all 0.13-based PRs](https://github.com/garden-io/garden/pulls?q=is%3Apr+is%3Aopen+base%3A0.13) to `main` (verify it) -> #3363
  * [x] Diff the working tree between the updated `main` and `0.13` to make sure there are no unexpected changes
* [x] Test and verify `garden self-update` command
